{% set data=load_setup_py_data() %}

package:
  name: release
  version: {{ data.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python ==3.6
    {% for dep in data.install_requires %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python ==3.6
    {% for dep in data.install_requires %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - release
  commands:
    - release --help

about:
  home: {{ data.url }}
  license: GNU General Public License v3 (GPLv3)
  license_family: GPL3
  summary: {{ data.description }}
